minimum_pre_commit_version: "3.5.0"

exclude: ^\.vscode/

repos:
  # 1. Hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        # args: [--fix=lf]  # Uncomment to force-convert to LF explicitly
      - id: detect-private-key
      - id: check-merge-conflict
      # Optional future:
      # - id: check-added-large-files
      # - id: debug-statements

  # 2. isort (normalize imports before black)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]

  # 3. black formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # 4. flake8 linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.4.26
        # files: ^src/  # Optionally scope to code only

  # 5. mypy (enable later once a baseline is established)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - types-PyYAML
  #         # - types-requests  # Prefer stubs over runtime pkg when possible
  #       args: [--ignore-missing-imports]

  # 6. Local commit message validation (commit-msg stage)
  - repo: local
    hooks:
      - id: commit-message-convention
        name: Commit message convention
        entry: python scripts/validate_commit_msg.py
        language: python          # Use 'system' if you prefer no venv overhead
        stages: [commit-msg]
