# config/config.yaml
monitor:
  timeout: 5
  retries: 3

logging:
  file: "logs/health_monitor.log"
  level: "INFO"

endpoints:
  - name: "Python.org"
    url: "https://python.org"
  - name: "Example Site"
    url: "https://example.com"
  - name: "Google"
    url: "https://google.com"
