name: Branch Name Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch naming convention
        run: |
          BRANCH="${{ github.head_ref }}"
          REGEX='^([a-z0-9]+(-[a-z0-9]+)*)/([0-9]+)-([a-z0-9]+(-[a-z0-9]+)*)$'
          if [[ ! "$BRANCH" =~ $REGEX ]]; then
            echo "Branch name '$BRANCH' does not match required pattern:"
            echo "[milestone-slug]/[issue#]-[feature-slug]"
            exit 1
          fi